config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets, only: [:index]
end

app/models/tweet.rb
class Tweet
  include ActiveModel::Model
  attr_accessor :text, :created_at
end

app/models/twitter_user.rb
class TwitterUser
  include ActiveModel::Model
  attr_accessor :name, :screen_name

  CONNECTION = $twitter

  def self.find(id)
    raw_user = CONNECTION.user(id)
    new(name: raw_user.name, screen_name: raw_user.screen_name)
  end

  def tweets(limit: 25)
    raw_timeline = CONNECTION.user_timeline(screen_name, count: limit)
    raw_timeline.map { |tweet| Tweet.new(text: tweet.full_text, created_at: tweet.created_at) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  rescue_from Twitter::Error::NotFound, with: :render_not_found

  def index
    if user_signed_in?
      @user = TwitterUser.find(params[:handle])
      @tweets = @user.tweets(limit: 25)
    else
      redirect_to new_user_session_path
    end
  end

  private

  def render_not_found
    render :not_found, status: 404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Stacksocial Challenge</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li> 
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<div class="container">
  <div class="panel">
    <div class="form-group">
      <h2>Enter a user's twitter handle to view their tweets</h2>
      <div class="form-control">
        <%= form_tag(tweets_path, method: :get) do %>
          <%= label_tag "twitter handle" %>
          <%= text_field_tag('handle')  %>
          <%= submit_tag 'Submit' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<%= render 'tweets/form' %>

<div class="container">
  <% unless params[:handle].nil? %>
    <ul class="list-group">
      <h3>Last tweets of <%= @user.name %> (@<%= @user.screen_name %>)</h3>
        <% @tweets.each do |tweet| %>
        <li class="list-group-item">
          <%= tweet.text %>
        </li>
        <% end %>
    </ul>
  <% end %>
</div>

app/views/tweets/not_found.html.erb
<%= render 'tweets/form' %>

<div class="container">
  <h3>User not found</h3>
</div>